name: project-check

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry --break-system-packages
          make install
      - name: Run linter
        run: |
          pip install flake8 --break-system-packages
          make lint
      - name: Run pytest
        run: |
          pip install pytest --break-system-packages
          pip install pytest-cov --break-system-packages
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
